### ISSUE TITLE
Nightly builds don't start hidden on Windows startup

### ISSUE THREAD

**Issue by BooBerry** [processhacker/processhacker#304] opened 2018-08-23 14:44 UTC
I've noticed for awhile now that the nightly builds of Process Hacker, with the **Start when I log on** and **Start hidden** boxes checked, still shows the Process Hacker window at startup (**-hide** is applied to the startup item for Process Hacker, but it doesn't seem to do anything). It does this with a clean Process Hacker 3.0.1844 (f34b6f64) install on Windows 10 Pro 1803 64-bit.

Any ideas?

**Comment by Eyremba** [comment] 2018-09-05 16:26
Seems like I found the issue by browsing my Registry-Editor...

`"C:\Program Files\Process Hacker\\ProcessHacker.exe"`

Shouldn't it be:

`"C:\Program Files\Process Hacker\ProcessHacker.exe"`
?

Maybe the `\\` is the reason why it does not work.

**Comment by BooBerry** [comment] 2018-09-07 11:30
Where's the registry key location you're editing?

I'm using the latest nightly build with the commit above, but it's still showing the window on Windows startup for me (and start hidden is indeed checked).

**Comment by Eyremba** [comment] 2018-09-07 13:38
> I'm using the latest nightly build with the commit above, but it's still showing the window on Windows startup for me (and start hidden is indeed checked).

I don't know how to fix this. Read what I wrote, for me, it wasn't even starting. Fixing the Registry just enables it to start if the autostart was not working before.

**Comment by dmex** [comment] 2018-09-08 00:04
> Maybe the \\ is the reason why it does not work.

Windows ignores extra path separators. I've tested the string and CreateProcess/ShellExecute/run dialog and command prompt ignore the extra separator and launch without issues.

> But it does not autostart into the Administrator mode, only into the normal mode

This is not supported.

> I'm using the latest nightly build with the commit above, but it's still showing the window on Windows startup for me (and start hidden is indeed checked).

You need to have at least one tray icon enabled via the View > Tray icons menu.

>  -hide is applied to the startup item for Process Hacker, but it doesn't seem to do anything

Try changing the StartHidden setting from 0 to 1

**Comment by BooBerry** [comment] 2018-09-08 01:31
> Try changing the StartHidden setting from 0 to 1

It already was, and still appears on startup. Oddly enough if I disable **Start when I log on** and manually start the app after Windows boots, it starts hidden. Very odd indeed.

**Comment by Eyremba** [comment] 2018-09-08 19:07
> Windows ignores extra path separators. I've tested the string and CreateProcess/ShellExecute/run dialog and command prompt ignore the extra separator and launch without issues.

But the autostart of PH was not working on my PC until I removed the second separator.

**Comment by dmex** [comment] 2018-09-12 07:01
> It already was, and still appears on startup. Oddly enough if I disable Start when I log on and manually start the app after Windows boots, it starts hidden. Very odd indeed.

I've made a few more changes in the latest nightly.

> But the autostart of PH was not working on my PC until I removed the second separator.

I tested it on Win7, Win8 and Win10 and wasn't able to reproduce the issue. I don't even know how you're getting multiple separators since we normalize the path (and remove duplicate separators) before configuring the autostart key...

There are only two things that currently screw-up autostart keys:

* RegisterApplicationRestart function (Win10 only)
Microsoft changed the RegisterApplicationRestart function to re-launch programs after a reboot/shutdown. This could launch a second instance of the program and trigger the single-instance code to focus the main window - so I've disabled RegisterApplicationRestart usage for now.

* Antivirus products 
A few companies have been doing absolutely outrageous (and in some cases illegal) activity towards our project recently and I would not be surprised if some AV registry filter callback modified the autostart key.

**Comment by BooBerry** [comment] 2018-09-12 14:04
> I've made a few more changes in the latest nightly.

I need to do more testing, but so far it seems to have done the trick, thanks!

**Comment by Eyremba** [comment] 2018-09-14 21:00
I'm using the newest version of Windows 10. So I think that it was maybe because of this RegisterApplicationRestart.

**Comment by dmex** [comment] 2018-09-16 12:47
> so far it seems to have done the trick, thanks!

Thanks for letting me know 👍 

> I think that it was maybe because of this RegisterApplicationRestart.

The only change I made was removing RegisterApplicationRestart so it looks like that was the problem :/

I guess we can close this for now but I'll track someone down at MS about why RegisterApplicationRestart ignores autostart and launches multiple instances.

**Closed by dmex** 2018-09-16 12:47 UTC
