### ISSUE TITLE
[Bug] Always on top : secondary windows behind primary window

### ISSUE THREAD

**Issue by KaKi87** [processhacker/processhacker#569] opened 2020-03-06 21:41 UTC
When Process Hacker is _always on top_, almost all secondary windows but _Hacker > Options_ and _View > System information_ will stay behind the main window instead of being on top of it.

Thanks

**Comment by KaKi87** [comment] 2020-04-08 13:46
Hello, any news on this ? Thanks

**Comment by dmex** [comment] 2020-04-09 06:43
Are you using the nightly builds or the v2.39 release? The issue with always on top was fixed in the nightly builds some time ago.

**Comment by dmex** [comment] 2020-04-15 13:51
> almost all secondary windows

Can you give me a list of windows you need fixed? I don't want to do it for every window because the implementation needs a major rewrite for Windows 10 after breaking changes by Microsoft.

**Comment by KaKi87** [comment] 2020-04-15 14:13
- Hacker > Run As
- Hacker > Plugins
- View > Windows
- Tools > Create Service
- Tools > Create Live Dump
- Tools > Inspect Executable File > (Properties)
- Tools > Pagefiles
- Tools > Network Tools > Ping address > (Ping)
- Tools > Network Tools > Traceroute address > (Tracing)
- Tools > Network Tools > Whois address > (Whois)
- Tools > Online Checks > Upload file to Hybrid-Analysis
- Tools > Online Checks > Upload file to VirusTotal
- Users > (*) > Properties
- Help > Log
- Help > About
- Services > Right click > Properties
- Services > Right click > Send to > (*)
- Disk > Right click > Inspect

I think you should find a way to fix this issue for all windows at once instead.

**Comment by dmex** [comment] 2021-01-25 09:20
Duplicate of #200 

I've referenced your comment over there to keep track.

**Closed by dmex** 2021-01-25 09:20 UTC

**Comment by stdedos** [comment] 2021-01-25 09:58
> > almost all secondary windows
> 
> Can you give me a list of windows you need fixed? I don't want to do it for every window because the implementation needs a major rewrite for Windows 10 after breaking changes by Microsoft.
> 
> 

Always funny to hear that 🤣

**Comment by dmex** [comment] 2021-01-25 10:06
@stdedos 

When tablet mode is enabled you don't receive the WM_SHOWWINDOW message... so most of the windowing code we were using hasn't been working properly... It's only Windows 10 and a major breaking change from previous versions.

**Comment by stdedos** [comment] 2021-01-25 13:05
What does that matter to PH? You don't target tablets (or tablet-mode); do you?

**Comment by dmex** [comment] 2021-01-25 13:42
> What does that matter to PH?

Older versions of Windows 10 can be toggled on or off without tablet hardware. Newer versions of Windows 10 can only toggle it on when there's compatible hardware.

 > You don't target tablets (or tablet-mode); do you?

If you toggle it on; It breaks a bunch of PH windows because they don't receive WM_SHOWWINDOW... I've been migrating code away from those messages where possible but it'll be an issue for anyone running PH on touch compatible laptops/hardware.

**Comment by stdedos** [comment] 2021-01-25 15:58
Ouch, ofc, but I wouldn't call really PH a "tablet-optimized" program 😝 

Real HW has way north of 100-200 processes, and for "fake HW" maybe PH is not the best option anyway. 
The usecase I can foresee would be that I win such a tablet, and since have "substance dependency" on PH for almost anything related to processes, I will try to install/use it regardless.
