### ISSUE TITLE
Display graph per GPU in System Information

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#718] opened 2020-10-27 21:21 UTC
Feature request: Please display one graph per GPU in System Information window, similarly as Windows built-it Task Manager does it.

I have Lenovo ThinkPad E490 laptop with two graphics cards, one is "Intel(R) UHD Graphics 620" the other is "Radeon (TM) RX 550X". It would be much more convenient when developing a 3D application.

In attachment there are two screenshots, one from Process Hacker version 3.0.3521, other from Task Manager.

![only_one_gpu_graph](https://user-images.githubusercontent.com/13893067/97363258-99db8080-18a2-11eb-8b86-5b6c9b63f83c.png)

![two_gpu_graphs](https://user-images.githubusercontent.com/13893067/97363269-9e079e00-18a2-11eb-8148-868e9eb9aff1.png)

**Comment by dmex** [comment] 2020-10-28 05:27
Duplicate of #65

The issue has been the difference between Windows 10 and earlier versions. Windows 7 and 8 don't have the same LUID identifiers needed for separating the devices across reboots.

**Closed by dmex** 2020-10-28 05:27 UTC

**Comment by lovelifezhenzhen** [comment] 2021-03-01 02:40
Do you mean that LUID identifiers is not unique for GPU adapters on Windows 10?

**Comment by dmex** [comment] 2021-03-01 07:07
@lovelifezhenzhen 

They're too unique and change with the wind. Reboot and they change, sleep and they change, update the driver and they change, execute pnputil /restart-device and they'll change, install windows updates and they'll change, connect a new monitor  etc... 

This is the complete opposite to LUIDs for other devices such as network adapters where the LUID only changes when you change the device socket/controller and they'll remain static across reboots and device changes. You can easily cache the NetLuidIndex and reuse later without it being invalidated unless its a different device and that's how PH is able to show adapter utilization for specific adapters because we cache NetLuidIndex and reuse it when calling functions like GetIfEntry/GetIfEntry2 with InterfaceLuid and easily querying the specific individual adapter utilization based on your preferences. 

You can't do that with graphics devices and D3DKMTOpenAdapterFromLuid and are forced to constantly poll and enumerate devices which is a major performance problem especially since we still support Windows 7 and 8 which don't have the concept of graphics LUIDs... So we cache it anyway but you'll run into the problem where updating the nvidia driver invalidates the LUID and prevents PH from showing utilization without restarting the program.

The other more recent and very major problem is that Microsoft completely broke the D3DKMTQueryStatistics function on recent versions of Windows 10 forcing you to use performance counters which are massive string arrays (parsing string arrays are a major performance issue in themselves) and cannot be easily integrated with the existing code while also removing the ability to query individual processes/adapters.

It's a shitshow... I think this was intentional by Microsoft to stop third party software from correctly showing GPU usage like Process Explorer and Task Manager... I really can't see any other reason for so many stupid design changes or why they're broken these functions 5 times in 3 years - so much for Windows backwards compatibility 🤷‍♂️

**Comment by lovelifezhenzhen** [comment] 2021-03-01 12:05
It seems to be less opening!
Do you know the detailed version of Windows 10 that broke the D3DKMTQueryStatistics function?

**Comment by dmex** [comment] 2021-03-01 13:06
> Do you know the detailed version of Windows 10 that broke the D3DKMTQueryStatistics function?

20H1 | May 2020 Update | 10.0.19041

It'll only return partial statistics and only for some processes. For example it'll report the correct usage until you start playing any graphics intensive games then both Process Explorer and Process Hacker report 1% utilization while Task Manager will report the correct utilization > 90%
