### ISSUE TITLE
Final release

### ISSUE THREAD

**Issue by alabotski** [processhacker/processhacker#649] opened 2020-07-22 05:17 UTC
When is the final version 3 coming out?
How many nightly versions are there?

**Comment by dmex** [comment] 2020-08-14 00:00
> When is the final version 3 coming out?

The release is being delayed by Microsoft.

> How many nightly versions are there?

There have been 672 nightly builds.

**Comment by ge0rdi** [comment] 2020-08-14 06:05
> The release is being delayed by Microsoft.

Can you explain how?

**Comment by dmex** [comment] 2020-08-15 05:13
> Can you explain how?

* Highly critical reliability issue that cannot be fixed solely because of internal Microsoft policy rather than a technical issue.
* Highly critical performance issue on 20H1 (build 19041 and above).
* GPU statistics has a major issue on 20H1 (build 19041 and above).
* API signature checks specifically designed to block Process Hacker and prevent competition.
* System components using hard-coded strings specifically designed to block Process Hacker and prevent competition.
* Process Hacker built-in Updater was disabled on approx. 400,000 machines by Microsoft.

In some other cases we would be required to delete and remove nearly every window and related process information from Process Hacker (e.g. Handles tab/Handle properties, Modules tab, Windows tab, GPU information, multiple process columns etc...) just to workaround the reliability issue.

I'll be posting details about these and other things in the next few weeks.

**Comment by ge0rdi** [comment] 2020-08-15 06:49
> I'll be posting details about these and other things in the next few weeks.

I'm really looking forward to it.

**Comment by ImSpecial** [comment] 2020-08-15 08:14
Cannot stand the place honestly, but this sounds like a good topic for reddit, they love a good "they took err jerbs!" story, get some upvotes and then hopefully get noticed by other media/blogs/whatever and maybe, just maybe something might happen. (probably not though...)

**Comment by brkerez** [comment] 2020-09-09 16:31
> * Highly critical reliability issue that cannot be fixed solely because of internal Microsoft policy rather than a technical issue.
> * Highly critical performance issue on 20H1 (build 19041 and above).
> * GPU statistics has a major issue on 20H1 (build 19041 and above).
> * API signature checks specifically designed to block Process Hacker and prevent competition.
> * System components using hard-coded strings specifically designed to block Process Hacker and prevent competition.
> * Process Hacker built-in Updater was disabled on approx. 400,000 machines by Microsoft.
> 
> In some other cases we would be required to delete and remove nearly every window and related process information from Process Hacker (e.g. Handles tab/Handle properties, Modules tab, Windows tab, GPU information, multiple process columns etc...) just to workaround the reliability issue.
> 
> I'll be posting details about these and other things in the next few weeks.

I'm looking forward to the details and despite it's useless to you I want to say that I feel I want to break something only by reading about this. Being active windows user and developer for 20 years it's tough to stay pragmatic and I'm sad/angry/... by the direction Microsoft is heading lately.

**Comment by cool-RR** [comment] 2020-09-27 10:11
Any update about this? I'm also looking forward to the next release.

**Comment by ImSpecial** [comment] 2020-09-27 18:40
I hope there's never a final release, and that dmex keeps doing what he does, and that Process Hacker continues to see updates for many many years to come.

**Comment by Farxial** [comment] 2020-11-23 16:10
> Highly critical reliability issue that cannot be fixed solely because of internal Microsoft policy rather than a technical issue.

Then how about two different versions: (A) for normal Windows versions and (B) for Windows 10, or just (A)?

> I hope there's never a final release, and that dmex keeps doing what he does, and that Process Hacker continues to see updates for many many years to come.

I hope so too.

But, as far as I understand, the final release here just means a major version, recommended for use (at least for new users). At the moment it is version 2.39, which is more than 4 years old. And this is a big deal: some users could use PH, but they may have a psychological barrier to not using nightly builds, so they can't reach the latest PH improvements, so they get less benefit from using PH.
But I may be wrong, please correct me if so.

But what is definitely true is that neither the well-being of users nor the well-being of PH should depend on the policies of some corporations. But, who thinks that I'm wrong here, note this: Microsoft itself does not provide users with embedded analytics tools like PH, shifting this work to third-party developers, so the existence and well-being of such tools and developers is implicitly being part of Microsoft policy too.

Sorry for my bad English.

**Comment by dmex** [comment] 2021-01-25 09:33
Closing as duplicate of #415

3.0 release can be tracked there.

**Closed by dmex** 2021-01-25 09:33 UTC
Labels: question

**Comment by anodynos** [comment] 2021-04-08 19:00
@dmex Are these problems non-existent with version 2.39? Is it still safe to use on a modern Windows 10 Pro? 

> * Highly critical reliability issue that cannot be fixed solely because of internal Microsoft policy rather than a technical issue.
> * Highly critical performance issue on 20H1 (build 19041 and above).
> * GPU statistics has a major issue on 20H1 (build 19041 and above).
> * API signature checks specifically designed to block Process Hacker and prevent competition.
> * System components using hard-coded strings specifically designed to block Process Hacker and prevent competition.
> * Process Hacker built-in Updater was disabled on approx. 400,000 machines by Microsoft.

PS: Thanks for this project!

**Comment by Biswa96** [comment] 2021-04-08 19:03
Define safe.

**Comment by dmex** [comment] 2021-04-12 16:46
@anodynos 

> Are these problems non-existent with version 2.39? Is it still safe to use on a modern Windows 10 Pro?

No idea... Microsoft refused to share the information stating we're "involved in the development of ransomware" and "attackers are monitoring your repository".

Their pages are still available here:
`https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:Win64/ProcHack`

`"apply only to modified versions of Process Hacker"` could mean our binaries or someone downloading the source code and modifying it... Microsoft isn't replying to anything so I have no idea if it's something that can actually be fixed (i.e. an actual problem with our source) vs just making the project closed-source and DMCA'ing everyone sharing the source.

**Comment by chris400** [comment] 2021-05-16 10:03
> Highly critical reliability issue that cannot be fixed solely because of internal Microsoft policy rather than a technical issue.
> Highly critical performance issue on 20H1 (build 19041 and above).
> GPU statistics has a major issue on 20H1 (build 19041 and above).

Are these things reproducible by you @dmex, i.e. do you "accept" these bugs?
