### ISSUE TITLE
Windows 10 Defender issue

### ISSUE THREAD

**Issue by eakteam** [processhacker/processhacker#520] opened 2019-12-11 23:26 UTC
Process Hacker is identified as "HackTool" in the last Windows 10 Update and Defender... The antivirus automatically remove the .exe file.
As workaround for the moment should add the .exe or app folder to exception list in the antivirus.

If there is any solution for this is would be great !
Best Wishes

**Comment by poizan42** [comment] 2019-12-12 11:02
Duplicate of #454

**Closed** 2019-12-13 13:11 UTC
