### ISSUE TITLE
History column maximum calculation

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#571] opened 2020-03-12 22:11 UTC
![image](https://user-images.githubusercontent.com/133706/76570756-b31ff000-64be-11ea-8cd5-68e490aae1ab.png)

* Cpu History: Ignore `System Idle Process`. For 40% utilization and 295 processes, it is usually complicated to identify _who_ is the offender (if there is any).
* Mem History: Something is really off with the graphs:
  I am suspecting, the collapsed graphs are the average of the collapsed processes, which is then compared against the biggest axis. This looks better:

  ![image](https://user-images.githubusercontent.com/133706/76570876-eebaba00-64be-11ea-9412-3d91fcc7e185.png)

  I'd still prefer though, that avast would appear "90%" full, and then scale the rest accordingly (idk what's the current scaling reasoning though)

The only "reliable" one appears to be I/O

**Comment by dmex** [comment] 2020-03-13 06:01
> Ignore System Idle Process. For 40% utilization and 295 processes, it is usually complicated to identify who is the offender (if there is any).

The system idle graph shows the recent idleness of the machine and not so much for identifying processes with usage?

> Mem History: Something is really off with the graphs: the collapsed graphs are the average of the collapsed processes

The graphs for collapsed processes do not include the process' children so you won't see a graph showing the totals for all the children as you do for the other column values - It's something we just haven't had time to fix yet.

**Comment by stdedos** [comment] 2020-03-14 11:21
> > Ignore System Idle Process. For 40% utilization and 295 processes, it is usually complicated to identify who is the offender (if there is any).
> 
> The system idle graph shows the recent idleness of the machine and not so much for identifying processes with usage. I don't see any value in hiding the graph for the idle process?

Don't hide it. Set its scaling to 0-100 (like the main CPU graph), and ignore its scaling for all the rest of the process graphs.

> > Mem History: Something is really off with the graphs: the collapsed graphs are the average of the collapsed processes
> 
> The graphs for collapsed processes do not include the process' children so you won't see a graph showing the totals for all the children as you do for the other column values - It's something we just haven't had time to fix yet.

👍

**Comment by dmex** [comment] 2020-03-14 11:31
> Don't hide it. Set its scaling to 0-100 (like the main CPU graph), and ignore its scaling for all the rest of the process graphs.

It doesn't scale. The utilization of the idle process is the opposide of the actual utilization or always fixed to the total minus the current (available - current = idle)... If your machine is utilizing 20% of the CPU then the idle utilization is 80% - If your machine is utilizing 90% then the idle utilization is 10%.

The more idle your machine the higher the idle process utilization. The cpu history graph is the same as the other graphs with fixed scaling at 0-100 but if your machine is always idle the graph is always near maximum.

**Comment by stdedos** [comment] 2020-03-14 12:02
Oooh ... okay.

I was thinking that History graphs scale among themselves, as a relative-cpu-history feature. I keep forgetting of this:

> All the graphs scale independently of other graphs/processes and all have separate states - The idle process graph doesn't affect what the other graphs are showing.

and seeing this all the time:

![image](https://user-images.githubusercontent.com/133706/76681458-90472600-65fb-11ea-8beb-bcb0ffd78737.png)

made me think that the scaling is broken.

_Side question: I keep trying to use this https://github.com/ShareX/ShareX/ to take a full screenshot of my full process list, but none of the scrolling events seem to work. Your problem or theirs?_

**Comment by dmex** [comment] 2020-03-15 13:37
> made me think that the scaling is broken.

The scaling is ok but the issue is the inclusion of child processes on the graphs when they're collapsed.

>  I keep trying to use this ... to take a full screenshot of my full process list, but none of the scrolling events seem to work. Your problem or theirs?

It would be a problem with our custom treelist control. I don't think the automation of the UI is something that should be permitted since it could be abused?

**Comment by stdedos** [comment] 2020-03-15 17:17
> > I keep trying to use this ... to take a full screenshot of my full process list, but none of the scrolling events seem to work. Your problem or theirs?
> 
> It would be a problem with our custom treelist control. I don't think the automation of the UI is something that should be permitted since it could be abused?

Your call, not mine. I like when things work the way they are supposed to. If your call is _automation can be abused_; your software, your rules 😄

**Comment by dmex** [comment] 2020-03-15 18:04
> If your call is automation can be abused; your software, your rules

I might be wrong so it's always up for a discussion?

**Comment by stdedos** [comment] 2020-03-15 18:15
You have this - a successful open-source software, "security companies" on top of you (for _no fucking reason_), and drawing heat from everyone abusing `peview.exe`; and that's the story just here.

![image](https://user-images.githubusercontent.com/133706/76707516-645d9a80-66f8-11ea-84cb-6a8c1d702b58.png)

I would be glad if I have 1k useful commits scattered in private repositories. I am good at _complaining_ on what doesn't work the way _I_ expect it to; and I am lucky enough that enough of the times people trust / see eye-to-eye with me. My _opinion_ is that scrolling events should work.

But then my opinion also is that no-one is looking out to harm people, and everyone is nice to everyone 😅

**Comment by dmex** [comment] 2020-06-28 07:58
Closing issue since resolved 👍

**Closed by dmex** 2020-06-28 07:58 UTC
