### ISSUE TITLE
Visually divide GPU nodes, per card

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#719] opened 2020-10-27 21:32 UTC
Feature request: Please add some kind of visual divider into GPU Nodes window.

I have laptop with two graphics cards, Intel and Radeon, but the GPU Nodes window is a mess. It is very difficult to orient itself and to see what is going on. I would appreciate GPU nodes of each graphics card to start on new line and to be separated by vertical space to distinguish them from previous graphics card. Now I need to mouse over each node to see its tooltip or to visually search for (3D) node type as it seems it is the first one shown for each graphics card. This is very uncomfortable to do, visually separating nodes for each card would benefit when developing a 3D application.

In attached screenshot you can see that I need to find 21st node (last column, 3rd row) to see what is going on on my second GPU.

Process Hacker version 3.0.3521.

![where_one_gpu_ends_and_other_starts](https://user-images.githubusercontent.com/13893067/97364273-17ec5700-18a4-11eb-8eb5-ed36b67081f1.png)

**Comment by dmex** [comment] 2020-10-28 05:12
> GPU nodes of each graphics card to start on new line 

The window should only show nodes for the one card not multiple cards per the recent node commit changes.

I'll close as duplicate of #718 and #65

**Closed by dmex** 2020-10-28 05:12 UTC
