### ISSUE TITLE
> ![image](https://user-images.githubusercontent.com/8224786/53713153-dc914f00-3e5a-11e9-89e2-80501b4f1963.png)

### ISSUE THREAD

**Issue by hjafari-could** [processhacker/processhacker#527] opened 2019-12-22 00:44 UTC
> ![image](https://user-images.githubusercontent.com/8224786/53713153-dc914f00-3e5a-11e9-89e2-80501b4f1963.png)
> ![image](https://user-images.githubusercontent.com/8224786/53713186-fdf23b00-3e5a-11e9-84e0-993987dccc45.png)
> We cant see current position.
> Add something like additional line ======= you are here =======, or other delimiter, or difference by color/boldness of new and old changes, or collapsed with + old changes by default.

_Originally posted by @hjafari-could in https://github.com/processhacker/processhacker/issues/384#issuecomment-568223078_

**Comment by dmex** [comment] 2019-12-22 17:46
Duplicate of #384

**Closed by dmex** 2019-12-22 17:46 UTC
