### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#1182] opened 2022-04-14 09:54 UTC
### Brief description of your issue

PH crashed

### Steps to reproduce (optional)

Update to the latest trunk revision
Lauch PH

### Expected behavior (optional)

No problems

### Actual behavior (optional)

Crash
![2022-04-14](https://user-images.githubusercontent.com/24621645/163361225-ce36e910-9f01-4e1d-afd0-3e39b5f1ea5d.png)

> ntdll.dll!RtlpWaitOnCriticalSection()
> ntdll.dll!RtlpEnterCriticalSectionContended()
> ntdll.dll!RtlEnterCriticalSection()
> WindowsCodecs.dll!DllGetClassObject()
> [Inline Frame] ProcessHacker.exe!PhGetClassObjectDllBase(void *) Line 7893
> 	at D:\Dev\ProcessHacker3\src\trunk\phlib\util.c(7893)
> [Inline Frame] ProcessHacker.exe!PhGetClassObject(wchar_t *) Line 7929
> 	at D:\Dev\ProcessHacker3\src\trunk\phlib\util.c(7929)
> ProcessHacker.exe!PhLoadPngImageFromResource(void * DllBase, unsigned int Width, unsigned int Height, const wchar_t * Name, unsigned char RGBAImage) Line 894
> 	at D:\Dev\ProcessHacker3\src\trunk\ProcessHacker\searchbox.c(894)
> ProcessHacker.exe!PhpSearchInitializeImages(_EDIT_CONTEXT * Context) Line 138
> 	at D:\Dev\ProcessHacker3\src\trunk\ProcessHacker\searchbox.c(138)
> ProcessHacker.exe!PhCreateSearchControl(HWND__ * Parent, HWND__ * WindowHandle, wchar_t * BannerText) Line 851
> 	at D:\Dev\ProcessHacker3\src\trunk\ProcessHacker\searchbox.c(851)
> [External Code]
> ProcessHacker.exe!PhInvokeCallback(_PH_CALLBACK * Callback, void * Parameter) Line 5688
> 	at D:\Dev\ProcessHacker3\src\trunk\phlib\basesup.c(5688)
> ProcessHacker.exe!PhMainWndInitialization(int ShowCommand) Line 230
> 	at D:\Dev\ProcessHacker3\src\trunk\ProcessHacker\mainwnd.c(230)
> ProcessHacker.exe!wWinMain(HINSTANCE__ * Instance, HINSTANCE__ * PrevInstance, wchar_t * CmdLine, int CmdShow) Line 249
> 	at D:\Dev\ProcessHacker3\src\trunk\ProcessHacker\main.c(249)
> [External Code]
> 

### Environment (optional)

```shell
3.0.9281.4754 Git-3cd4b4ab
Windows 11 21H2
```

**Comment by skipik** [comment] 2022-04-14 11:02
Oh looks like it happened one time only. Another launch attemp was succkessfull with no problems.

**Comment by dmex** [comment] 2022-04-19 07:24
Duplicate of #1163

> ntdll.dll!RtlpWaitOnCriticalSection

This function shouldn't ever be crashing so it;s likely caused by some sort of injection/hooking by third party applications. Since there's a few of these tickets please use #1163 for tracking.

**Closed by dmex** 2022-04-19 07:24 UTC
Labels: bug, needs investigation
