### ISSUE TITLE
KProcessHacker doesn't work on Windows 10 build 21349

### ISSUE THREAD

**Issue by TheEragon** [processhacker/processhacker#898] opened 2021-05-25 07:40 UTC
KProcessHacker compiled from master doesn't work on Windows 10 build 21349.  The issue is in function `KpiPopulateKnownDllExtents` which is called from `DriverEntry` but fails with error 0xc0000141.

**To Reproduce**
1. Install Windows 10 build 21349
2. Enable test signing
3. Compile KProcessHacker
4.  Test new KProcessHacker

**Expected behavior**
ProcessHacker should be able to connect to KProcessHacker

**Additional context**
It seems that ntdll is loaded into the process, but PTEs are not valid and `ZwQueryVirtualMemory` fails.

```
0: kd> !vad
VAD             Level         Start             End              Commit
ffffd00da1405350  2           38420           385c8               0 Mapped  Exe  READONLY           \Windows\SysWOW64\ntdll.dll
ffffd00d9cab81a0  1           7ffe0           7ffe0               1 Private      READONLY           
ffffd00d9cab8150  0           7ffee           7ffee               1 Private      READONLY           
ffffd00da1405ad0  2        208f8420        208f8626               0 Mapped  Exe  READONLY           \Windows\System32\ntdll.dll
ffffd00da14052b0  1        208f8630        208f8661               0 Mapped  Exe  READONLY           \Windows\System32\vertdll.dll
ffffd00da141d9f0  2        208f8670        208f8670               0 Mapped       READWRITE          Pagefile section, shared commit 0x1

Total VADs: 6, average level: 2, maximum depth: 2
Total private commit: 0x2 pages (8 KB)
Total shared commit:  0x1 pages (4 KB)

0: kd> !vad ffffd00da1405ad0 1

VAD @ ffffd00da1405ad0
  Start VPN             208f8420  End VPN         208f8626  Control Area  ffffd00da149a8a0
  FirstProtoPte ffff918a1b242000  LastPte ffff918a1b243030  Commit Charge                0 (0n0)
  Secured.Flink                0  Blink                  0  Banked/Extend                0
  File Offset                  0  
      ImageMap ViewShare READONLY          

ControlArea  @ ffffd00da149a8a0
  Segment      ffff918a1b664690  Flink      ffffd00db4741ba0  Blink        ffffd00da1405b30
  Section Ref                 2  Pfn Ref                 178  Mapped Views               7c
  User Ref                   7e  WaitForDel                0  Flush Count              ab88
  File Object  ffffd00da1a29c20  ModWriteCount             0  System Views             4b72
  WritableRefs           480021  PartitionId                0  
  Flags (a0) Image File 

      \Windows\System32\ntdll.dll

Segment @ ffff918a1b664690
  ControlArea       ffffd00da149a8a0  BasedAddress  00007ffeb46c0000
  Total Ptes                     207
  Segment Size                207000  Committed                    0
  Image Commit                     f  Image Info    ffff918a1b6646d8
  ProtoPtes         ffff918a1b242000
  Flags (ce8e0000) ProtectionMask 

0: kd> !pte 00007ffeb46c0000
                                           VA 00007ffeb46c0000
PXE at FFFFA452291487F8    PPE at FFFFA452290FFFD0    PDE at FFFFA4521FFFAD18    PTE at FFFFA43FFF5A3600
contains 0000000000000000
contains 0000000000000000
not valid
```

@jxy-s any ideas what could be the cause?

**Comment by jxy-s** [comment] 2021-05-25 17:14
Thanks for the info @TheEragon I'll grab update to that version and try to reproduce.

**Comment by jxy-s** [comment] 2021-05-26 00:41
They stopped mapping ntdll as an image in `System`. On that version of 21H1 they are mapping it as data. Which means ntdll doesn't get mapped to the expected transfer address.

Pre-21H1:
```
0: kd> !vad
VAD             Level         Start             End              Commit
ffffc30afbc866e0  2           77980           77b19               9 Mapped  Exe  EXECUTE_WRITECOPY  \Windows\SysWOW64\ntdll.dll
ffffc30afb05ad80  1           7ffe0           7ffe0               1 Private      READONLY           
ffffc30afb05af10  0           7ffe6           7ffe6               1 Private      READONLY           
ffffc30b0047b7f0  2        25ec95c0        25ec95c0               0 Mapped       READWRITE          Pagefile section, shared commit 0x1
ffffc30afbc865a0  1       7ffd7b540       7ffd7b570               9 Mapped  Exe  EXECUTE_WRITECOPY  \Windows\System32\vertdll.dll
ffffc30afbc85a60  2       7ffd7b580       7ffd7b76f              16 Mapped  Exe  EXECUTE_WRITECOPY  \Windows\System32\ntdll.dll
```

21H1:
```
2: kd> !vad
VAD             Level         Start             End              Commit
ffffc8895fe8ff60  2           1dfc0           1e168               0 Mapped  Exe  READONLY           \Windows\SysWOW64\ntdll.dll
ffffc8895f2c0510  1           7ffe0           7ffe0               1 Private      READONLY           
ffffc8895f2c0740  0           7ffe9           7ffe9               1 Private      READONLY           
ffffc8895fe8f2e0  2        1ff1dfc0        1ff1e1c6               0 Mapped  Exe  READONLY           \Windows\System32\ntdll.dll
ffffc8895fe8f380  1        1ff1e1d0        1ff1e201               0 Mapped  Exe  READONLY           \Windows\System32\vertdll.dll
ffffc889635168b0  2        1ff1e210        1ff1e210               0 Mapped       READWRITE          Pagefile section, shared commit 0x1
```

So, when querying the virtual memory using the transfer address for the known dll section. It returns invalid address since it isn't mapped as an image in `System`.

FWIW, the build I'm looking at is this:
```
2: kd> vertarget
Windows 10 Kernel Version 21387 MP (4 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 21387.1.amd64fre.co_release.210518-1436
Machine Name:
Kernel base = 0xfffff805`27400000 PsLoadedModuleList = 0xfffff805`280296b0
Debug session time: Tue May 25 18:39:35.754 2021 (UTC - 6:00)
System Uptime: 0 days 0:06:40.524
```

**Comment by jxy-s** [comment] 2021-05-26 02:20
I have some thought on how we might address this. Going to think on it for a bit.

**Comment by TheEragon** [comment] 2021-05-26 08:35
Just a note, this is not 21h1 as I stated before, it's 21h2 or whatever MS will call it.

**Comment by jxy-s** [comment] 2021-05-26 23:30
@TheEragon fix is merged, I verified it on my end. I'm going to close this issue. If you have time, I would appreciate if you would run through your reproduction again. If you continue to run into problems please let me know.

**Closed** 2021-05-26 23:31 UTC
Labels: bug

**Comment by TheEragon** [comment] 2021-05-27 08:28
Thanks, now it seems to work just fine, even with the newest build 21390 👍
