### ISSUE TITLE
Panel Sway

### ISSUE THREAD

**Issue by LIMUNADE** [processhacker/processhacker#594] opened 2020-04-08 11:46 UTC
[As you can see](https://cdn.discordapp.com/attachments/218029592382799874/697410800335192065/image.png) this visual problem bother me for over a few month already. I'm using 3.0.2975 version.

**Comment by dmex** [comment] 2020-04-08 13:38
The dark theme menu should be fixed in the latest nightly v3.0.2977 

Duplicate of #570

**Closed by dmex** 2020-04-08 13:38 UTC
