### ISSUE TITLE
F5 doesn't refresh process list when the interval is above 1 second

### ISSUE THREAD

**Issue by hoffr** [processhacker/processhacker#813] opened 2021-02-23 02:15 UTC
**Describe the bug**
Pressing F5 does nothing if kernel-mode driver is enabled **EDIT** AND the program is running as admin, AND a refresh interval larger than 1s is selected.

**To Reproduce**
Steps to reproduce the behavior, **edited**:
1. clean slate
2. select an auto-refresh interval larger than 1s
3. enable kernel mode driver and relaunch
4. now relaunch as admin
5. press f5 and be sad

**Expected behavior**
f5 should probably work lol

**Desktop (please complete the following information):**
 - OS: Present in Win7 and Win10 20H2

**Additional context**
This issue is present in nightly v3.0.3178 & v3.0.3842, but not in stable v2.3.9

**Comment by ImSpecial** [comment] 2021-02-25 01:30
v3.0.3842 here and cannot reproduce this, my f5 refresh works as expected.

**Comment by dmex** [comment] 2021-02-25 03:39
> Present in Win7 and Win10 20H2

I couldn't reproduce on either machines. You probably have some third party software injecting/hooking something causing the delay.

**Comment by hoffr** [comment] 2021-02-25 04:50
I was slightly off, the issue seems to happen only under the following conditions: when the kernel-mode driver is enabled, the program is running as admin, AND an auto-refresh interval larger than 1s is selected. OP has been updated

**Comment by dmex** [comment] 2021-02-25 05:47
This isn't related to the driver... Somehow the NT timer doesn't enter an alterable wait when the timeout > 1000 breaking the provider implementation.

**Comment by ImSpecial** [comment] 2021-02-25 05:47
With 2 seconds, 5 seconds, and 10 seconds, I will cannot reproduce, f5 and the button both work works as expected.

**Comment by dmex** [comment] 2021-02-25 05:49
@ImSpecial 

I've confirmed the bug but now need to figure out why the alterable wait doesn't happen.

**Comment by ImSpecial** [comment] 2021-02-25 05:51
You calling me a liar dmex?

**Comment by dmex** [comment] 2021-02-25 05:56
@ImSpecial 

Yep 😘

It's easily reproducible after changing the interval >= 5, exiting the application and relaunching. If you just change the interval then it won't work because the NT timer was already initialized with the lower value before it was changed.

**Comment by ImSpecial** [comment] 2021-02-25 05:58
Ah, well I didn't relaunch PH, also my ProcessHacker.exe.settings.xml is set to Read-only. :P

**Comment by dmex** [comment] 2021-02-27 22:04
@hoffr

This was fixed in the latest nightly build. Good catch, thanks for reporting it 👍

@ImSpecial 
> ProcessHacker.exe.settings.xml is set to Read-only

Setting a file as read only doesn't prevent kernel drivers from modifying the file while its being loaded since the file data transitions through kernel filter callbacks. They can add or remove data after its loaded from disk but before the data is copied into application memory then later strip out that data before its saved back to disk.

The only way to prevent that is using runtime encryption/decryption of the file content which hasn't been added yet.

**Closed by dmex** 2021-02-27 22:04 UTC
Labels: bug
