### ISSUE TITLE
Error updating to latest version

### ISSUE THREAD

**Issue by gemal** [processhacker/processhacker#731] opened 2020-11-02 08:51 UTC
In 95% of the cases I want to update the application I get the following dialog:

![image](https://user-images.githubusercontent.com/69105/97847948-ad4a7980-1cf0-11eb-83e3-f6eddb5236b2.png)

it comes after this:

![image](https://user-images.githubusercontent.com/69105/97848163-f7335f80-1cf0-11eb-8663-af21f30d3138.png)

![image](https://user-images.githubusercontent.com/69105/97847962-b20f2d80-1cf0-11eb-8a90-45c6b2f43f5d.png)

I dont have any custom antivirus installed

Is there a way to get a debug/log entry so see what is wrong?

**Comment by gemal** [comment] 2020-11-02 08:56
it doesn't happen all the time but in most cases. How can I debug/log something to help find the cause of this?

**Comment by VictorVG** [comment] 2020-11-02 09:43
You will need .PDB files next to the binaries of the same name and the source code lying along the same path that was when the .PDB was created. Then, if the dump decryption fails, the debugger from Visual Studio will point to the line in the source where it originated.

**Comment by gemal** [comment] 2020-11-02 09:45
> 
> 
> You will need .PDB files next to the binaries of the same name and the source code lying along the same path that was when the .PDB was created. Then, if the dump decryption fails, the debugger from Visual Studio will point to the line in the source where it originated.

ok that doesn't seem like a solution I can do sorry.
Perhaps the installer/updater could write a log entry in the windows log when it encounters an error?

**Comment by Michedelic** [comment] 2020-11-03 00:09
I have this issue, apparently Windows Defender is detecting it as a trojan and blocking it. Had to download the executable from the main nightly page

**Comment by nithax** [comment] 2020-11-03 19:55
> I have this issue, apparently Windows Defender is detecting it as a trojan and blocking it. Had to download the executable from the main nightly page

same here. Trojan:Win32/Wacatac.C!ml

**Comment by dmex** [comment] 2020-11-03 19:57
Can you please upload screenshots from defender?

**Comment by nithax** [comment] 2020-11-03 20:06
[](https://i.imgur.com/ZF3KYtg.png)

directly from the auto-updater of the app.

**Comment by dmex** [comment] 2020-11-04 00:57
Duplicate of #454

**Closed by dmex** 2020-11-04 00:57 UTC
