### ISSUE TITLE
Revert: Menu bar menus now disappear based on mouse movement [3.0.2898]

### ISSUE THREAD

**Issue by Tharn** [processhacker/processhacker#547] opened 2020-01-29 13:01 UTC
This is very irritating. A recent-ish change introduced the 'feature' that when the mouse cursor moves off an opened menu bar menu, the menu collapses. I'm proposing this change be reverted, as it was much more comfortable to use the program before.

When the user clicks an item on the menu bar, the user **intends** to use the menu bar. Don't close it on him unless he **clicks** outside the menu.

The right-click context menu does not disappear this way either. Please make regular menus behave the same way again.

**Comment by dmex** [comment] 2020-01-29 13:23
> A recent-ish change introduced the 'feature' that when the mouse cursor moves off an opened menu bar menu, the menu collapses.

This is not reproducible on three of my own machines and the main menu remains active unless you click somewhere. 

Are you sure its not caused by some third party software such as games or antivirus (14 companies/products are maliciously targeting/force rebooting/terminating/injecting into Process Hacker and patching system calls) ?

**Comment by Tharn** [comment] 2020-01-29 14:48
I'm not using any third party software. I run a very lean system. I have this behavior on both my laptop and desktop running 2895 and 2898 respectively. Will try to see if it's Process Hacker plugins?

**Comment by pasha-zzz** [comment] 2020-01-30 06:35
I open menu and move cursor from it. Menu hides after 6 sec.

**Comment by dmex** [comment] 2020-01-30 07:26
> Menu hides after 6 sec.

That would be this change from July 2018: https://github.com/processhacker/processhacker/commit/30e4061540120c62d65177bf2908b7c06343c4ea

**Comment by dmex** [comment] 2020-01-30 07:50
> the mouse cursor moves off an opened menu bar menu, the menu collapses.

I misunderstood this as the menu closing immediately after moving the mouse away from the menu and not the menu timeout closing the menu (MNS_AUTODISMISS)... 

I've updated the nightly build without the flag 👍

**Closed by dmex** 2020-01-30 07:50 UTC

**Comment by Tharn** [comment] 2020-01-30 19:31
I did mean the menu closing immediately after moving the mouse off it. Weird.

**Comment by dmex** [comment] 2020-01-31 09:09
> something was wonky anyway.

user32 internally creates a hidden timer for the menu when using MNS_AUTODISMISS and it would be the new "Timer coalescing" feature on Windows 10 shifting the interval to match the internal of a group of other timers and thus causing the timer to fire much earlier than the documented 10 seconds.

This is also why its 10sec on my machine and less than 1sec on your machine and less than 6sec on @pasha-zzz 's machine... The documentation specifies 10 seconds and those changes to the timer interval render the MNS_AUTODISMISS flag unusable and a regression from earlier versions of Windows - I don't expect Microsoft will fix this anytime soon.
