### ISSUE TITLE
"Enable auto focus to search box" with "Hide when closed" doesn't work

### ISSUE THREAD

**Issue by FicoPrieto** [processhacker/processhacker#663] opened 2020-08-20 15:50 UTC
# System Info
```yaml
ProcessHacker: 3.0.3263   x64
Windows:       10.0.19041 x64
```

# Settings
```yaml
Options: 

  General: 
    Hide when closed:                           true
    Process Hacker is the default Task Manager: true
    
  ToolStatus: 
    Enable auto focus to search box: true
```

# Working
- start a new instance of PH via `Ctrl + Shift + Escape`  
  (*search box is focused*)
- execute `Menu > Hacker > Exit`
- start a new instance of PH via `Ctrl + Shift + Escape`  
  (*search box is focused*)

# Not Working
- start a new instance of PH via `Ctrl + Shift + Escape`  
  (*search box is focused*)
- click the `✖` button the title bar to hide PH
- open the existing instance of PH via `Ctrl + Shift + Escape`  
  (*search box is **not** focused*)

# Notes

As shown in the GIF below, the search query is persisted when reopening an existing instance of PH. I'm not sure if that is the case when the auto-focus feature is functional, but it's definitely a nice feature to have. Ideally, the previous query would be pre-selected on auto-focus so that it can be quickly overwritten if needed.

&nbsp;  
![ProcessHacker](https://user-images.githubusercontent.com/22942079/90792941-1bc69080-e2d9-11ea-8ce1-9b62458d2640.gif)

**Comment by dmex** [comment] 2020-08-20 23:40
Duplicate of #576 ?

**Comment by FicoPrieto** [comment] 2020-08-21 00:55
@dmex

#576 seems to be the opposite of this issue.

My search box is not acquiring focus, whereas their search box is not releasing focus.

**Comment by dmex** [comment] 2021-01-25 10:15
Fixed in the latest nightly build 👍

**Closed by dmex** 2021-01-25 10:15 UTC
Labels: bug
