### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml detected in processhacker-3.0.4021-bin

### ISSUE THREAD

**Issue by peterek102** [processhacker/processhacker#882] opened 2021-04-29 22:05 UTC
Both 32 and 64 bit

![image](https://user-images.githubusercontent.com/13313433/116624183-c3579080-a947-11eb-9a71-415ce331a59c.png)

**Comment by dmex** [comment] 2021-05-01 05:31
Duplicate of #454

**Closed by dmex** 2021-05-01 05:31 UTC
