### ISSUE TITLE
Services using 20%cpu

### ISSUE THREAD

**Issue by boistordu** [processhacker/processhacker#893] opened 2021-05-17 02:12 UTC
**Describe the bug**
Hi,
Have this problem on only one host which is a tablet. The other desktop host doesn't seem to have that problem. 

If I m not running processhacker in admin mode it is using 20% of cpu. And for a tablet that's a lot as you can imagine. 
For what I can see there is no reason for that. I do understand that services is just a collapsed version of everything else as a service but the problem here is that it disappears completely if I run in admin mode.
And there are no added process that appears in admin mode.
So from 20% cpu I go to 3% cpu...

**To Reproduce**
I don't know yet 

**Expected behavior**

**Screenshots**
Do you need a gif ? 

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Version will add the exact version later 

**Additional context**
It's a tablet so because of the limited cpu is highly visible. Maybe the desktop have the same problem but since the cpus are way higher end it's maybe less visible 
Sorry if it s a duplicate problem

**Comment by dmex** [comment] 2021-05-20 12:26
> The other desktop host doesn't seem to have that problem.

How strange... Can you try changing the EnableServiceNonPoll setting to 1 and restarting PH?

![image](https://user-images.githubusercontent.com/1306177/118978065-3c339080-b9ba-11eb-8e21-c24587c6b7be.png)

**Comment by boistordu** [comment] 2021-05-21 16:09
Okey and do you want that I reboot also just to see if it s only when rebooting or just closing and restart the app?

**Comment by dmex** [comment] 2021-05-21 17:20
> closing and restart the app

You only need to open/close the app after changing the settings

**Comment by boistordu** [comment] 2021-05-24 21:22
I don't see where you want me to change that

**Comment by boistordu** [comment] 2021-05-24 21:40
Found it you meant in settings.xml
Indeed then the services.exe is not giving me problems then. 
What do you need to debug this?

As far as I can see it doesn't happen on my different desktops

It s only on this tablet. It s not related to windows itself since it has been the case for 2 years now and so plenty of windows 10 pro version. 
And now it s a fresh installation so it s not that either. So this is related to something else

**Comment by dmex** [comment] 2021-05-25 13:19
> As far as I can see it doesn't happen on my different desktops
> not related to windows itself
> What do you need to debug this?

It's a problem with windows that's existed for over 15 years. Nobody has been able to figure out what causes the problem or why it only affects some machines and only some users and not everyone others.

It's the exact same OpenServiceW/QueryServiceConfigW function with the exact same flags for everyone... For some lucky few the services.exe process goes ballistic with maximum processor utilization for some machines which we assume is from some bug causing an infinite loop and nobody can reproduce the issue except for a very few limited people - 5 reports in the last decade out of 15 million downloads/installations. 

services.exe is a Microsoft process/component and we're using these documented functions the exact same way for everyone - we cannot modify their behaviour or fix whatever issue is happing in that process because its not ours and outside our control... So instead we added that setting which disables most of these service functions thereby working around that issue at the cost of dysfunctional/incorrect service information.

There isn't any other solution until Microsoft fix whatever issue or bug causes this problem in their services.exe component. So since that setting resolves the issue we'll close this ticket 👍

---------
(internal note to reference ticket 454 since Microsoft refusing to fix this issue after so many years likely be deliberate anti-competitive behaviour similar to #454)

**Closed by dmex** 2021-05-25 13:19 UTC

**Comment by boistordu** [comment] 2021-05-26 13:37
Okey so it can't be related a specific component which would be used in those machines for example ? Maybe some third party that would need also those services.exe whether it s a biometric sensor or a gravitational sensor or something like that?

**Comment by dmex** [comment] 2021-05-27 06:39
> related a specific component which would be used in those machines for example ?

A third party application might be setting a value in their service configuration using the wrong format or something which services.exe doesn't handle correctly?

> a biometric sensor or a gravitational sensor or something like that?

services.exe doesn't have any third party codes. All it does is query/set configuration in the registry here:
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services`

It's entirely possible a program is setting a value in there causing the issue but there are so many that who knows what it does or why.
