### ISSUE TITLE
Error C2065: TraceControlgetTraceGuidList: An undeclared identifier

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#933] opened 2021-07-23 05:23 UTC
Error C2065: TraceControlgetTraceGuidList: An undeclared identifier

**To Reproduce**

Just build project

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Vista]

**Additional context**

**Comment by Biswa96** [comment] 2021-07-23 05:24
Duplicate of previous issue https://github.com/processhacker/processhacker/issues/932

**Comment by VictorVG** [comment] 2021-07-23 05:59
And fixed it :)

**Closed** 2021-07-23 11:26 UTC
