### ISSUE TITLE
Gpu performance counters don't work.

### ISSUE THREAD

**Issue by kotenok2000** [processhacker/processhacker#825] opened 2021-03-09 21:56 UTC
**Describe the bug**

**To Reproduce**
1. Hardware Accelerated GPU Scheduling
2. Reboot windows
3. open process hacker
4. Click view in menu bar
5. click system informationn
6. select gpu graph
7. press nodes button
8. Run some gpu intensive process(boinc)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Microsoft Windows [Version 10.0.19042.867]
pro

**Additional context**
my gpu is NVIDIA GeForce GTX 1650

**Comment by MagicAndre1981** [comment] 2021-03-11 07:34
have you enabled the GPU monitoring via config xml?

```
<setting name="ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters">1</setting>
<setting name="ProcessHacker.ExtendedTools.EnableGpuMonitor">1</setting>
```

**Comment by dmex** [comment] 2021-03-15 03:47
Duplicate of #514

**Closed by dmex** 2021-03-15 03:47 UTC
