### ISSUE TITLE
Description column is empty

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#867] opened 2021-04-07 20:24 UTC
**Describe the bug**

the Description column is empty for all proceses

**To Reproduce**
1. run PH on Windows 8.1 
2. Description colum is empty

**Expected behavior**

Description column shows Description for process like it always did

**Screenshots**

![image](https://user-images.githubusercontent.com/8274816/113929030-d61af180-97ef-11eb-8345-e77197fedab2.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 x64

**Additional context**

PH 3.0.3963 (77cf5cc)

**Comment by Biswa96** [comment] 2021-04-07 20:30
Can't reproduce the issue in Win10 x86_64 with same PH version/commit.

**Comment by dmex** [comment] 2021-04-07 22:25
> PH 3.0.3963

You're running an older version and was fixed with 3965

**Closed by dmex** 2021-04-07 22:25 UTC

**Comment by MagicAndre1981** [comment] 2021-04-08 04:23
> You're running an older version and was fixed with 3965

at time of writing it was latest version offered via update. 3965 fixed it, thanks.
