### ISSUE TITLE
Just a small UI bug that shows two rows of tabs

### ISSUE THREAD

**Issue by poqdavid** [processhacker/processhacker#980] opened 2021-08-31 09:27 UTC
**Describe the bug**
Just a small UI bug that shows two rows of tabs

**To Reproduce**
1. Updating to Version: 3.0.4322 (24c634e)
2. Lunch ProcessHacker without minimizing (cause once its minimized that effect is gone)

**Expected behavior**
Show two rows of tabs once its openned

**Screenshots**
![ProcessHacker_2021-08-31_02-08-40](https://user-images.githubusercontent.com/9592210/131477960-755adf5d-0a07-4acf-808c-fa6e89ddfba1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64Bit
 - Version 21H1 (19043.1165)

**Additional context**

**Comment by dmex** [comment] 2021-08-31 09:35
> Steps to reproduce the behavior

I can't reproduce the bug based on what's provided.

**Comment by poqdavid** [comment] 2021-08-31 09:48
> > Steps to reproduce the behavior
> 
> I can't reproduce the bug based on what's provided.

Hmm odd I just simply updated all the files and its happening I literally didn't do anything unzip everything except my config can that be it?

**Comment by dmex** [comment] 2021-08-31 12:33
Try updating to r4330

**Comment by poqdavid** [comment] 2021-09-01 07:05
> Try updating to r4330
> 
> If it still happens then try disabling the dark theme.

I did all that a few times with reboots and its all the same result

**Comment by dmex** [comment] 2021-10-31 11:15
Fixed in the latest nightly update 👍

**Closed by dmex** 2021-10-31 11:15 UTC
