### ISSUE TITLE
Re-add Sandboxie support

### ISSUE THREAD

**Issue by kristibektashi** [processhacker/processhacker#728] opened 2020-10-31 15:31 UTC
On the latest Nightly build of Process Hacker SbieSupport.dll automatically gets deleted when I launch Process Hacker. On version 2.39 it works just fine (and is even included by default). Why does this happen?

**Comment by Skibicki** [comment] 2020-10-31 20:13
It is a compatability issue with some security features.  #233
Fyi: Sandboxie was made Open Source.
Recent activity here: https://github.com/sandboxie-plus/Sandboxie

**Comment by kristibektashi** [comment] 2020-10-31 20:56
I don't have any antivirus. Why I still can't use it. Also, if I install both process hacker v2.39 and the latest nightly build then version 2.39 simply doesn't open id sbiesupport.dll is installed (if I uninstall nightly build it works). Why does the nightly build blacklist affect the stable version (v2.39)?

**Comment by kristibektashi** [comment] 2020-10-31 20:58
BTW I have installed sandboxie plus

**Comment by Skibicki** [comment] 2020-10-31 21:04
A setting is probably changed when a new version is installed. Try the PortableApps version of Process Hacker if you want isolated settings.

**Comment by dmex** [comment] 2020-11-02 14:52
> 2.39 it works just fine

You need to change the `EnableSafeDefaultPlugins` setting to zero to enable non-default plugins.

> Why does the nightly build blacklist affect the stable version

They're both using the same code. I've added the above setting to enable the legacy blocklist.

> It is a compatability issue with some security features.

The problem is that binaries containing "SbieDll.dll" strings are automatically considered malware by security products. I removed at least 5 false positives by removing support for Sandboxie.

Sandboxie was discontinued so the Process hacker support was removed from the main project and retired here: https://github.com/processhacker/plugins-extra/tree/master/SbieSupport

> Sandboxie was made Open Source and there are two forks.

The SbieSupport still sometimes gets minor updates. Those forks should work fine with the current version but you need to compile it.

**Comment by kristibektashi** [comment] 2020-11-08 15:09
Now Process Hacker won't even open when I have sbiesupport.dll loaded (nightly version, v2.39 works fine). I have Sandboxie-Plus which is installed on a different directory that the default one (C:\Program Files\Sandboxie-Plus instead of C:\Program Files\Sandboxie) and I noticed an interesting bug. Process hacker opens fine when I have selected the unexisetent sbiedll.dll on C:\Program Files\Sandboxie but when I select the correct one it crashes. If I have both version 2.39 and nightly version installed then same thing happens on v2,39 except it won't open at all if I select the correct dll (it works fine with the wrong dll selected but obviously there is no sbie support then) If I only have v2.39 installed then it works fine. Note: I used the version of sbiesupport.dll included with v2.39 setup on v2.39 and the manually compiled version on nightly version.

BTW I tested this a few days ago with nightly build v3.0.3559 so I don't know if this is fixed yet. I think sbiesupport.dll is broken.

**Comment by dmex** [comment] 2020-11-08 20:46
> when I select the correct one it crashes
> have both version 2.39 and nightly version installed then same thing happens on v2,39

I found SbieDll.dll terminates the process with code -1 (0xffffffff).

The issue will only become visible for users with the nightly builds as they enable Windows 10 mitigation policies which SbieDll does not support. You have to delete the IFEO key to prevent the crash but it won't fix:

1) SbieDll terminating the application when it fails at something.
2) SbieDll modifying the calling process instead of using the child process.

These are upstream issues with their DLL causing the crashes with the nightly. You can get the same working behaviour as v2.39 by deleting the IFEO key but that probably won't be supported at some point.

So they need to make their DLL compatible with Windows 10 mitigation policies by using a service/child process (or at minimum stop killing the process when their DLL doesn't load).

**Comment by DavidXanatos** [comment] 2021-02-15 18:41
@dmex do you know which mitigation policies in particular cause the problem?

Also I would suggest not to use the SbieDll.dll to interface but instead talk to the driver directly, here is an example of such a interface implementation: https://github.com/DavidXanatos/TaskExplorer/blob/master/TaskExplorer/API/Windows/SandboxieAPI.cpp

**Comment by kristibektashi** [comment] 2021-05-07 20:24
How is Sandboxie support for Process Hacker coming along? @dmex @DavidXanatos

**Comment by kristibektashi** [comment] 2021-07-23 14:48
This issue is long dead. Should I close it?

**Comment by dmex** [comment] 2021-07-23 14:55
@kristibektashi 

Well @DavidXanatos has been making a lot of changes to Saneboxie recently which might have fixed the compatibility issues: https://github.com/sandboxie-plus/Sandboxie

> Should I close it?

I haven't tested any of the recent changes and was going to leave it open until we know the API is working or dead.

> sandboxie-plus

@DavidXanatos 

what happened to the license header? 😋
https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/common/verify.c

**Comment by DavidXanatos** [comment] 2021-07-23 17:23
The API is changed, also I'm not sure if it's the best approche to load the SbieDll.dll just to use a few API's as then updating sandboxie will prompt to kill process hacker if its running.

Hence for TE I went with calling the driver directly, also its not needed to use the KillAll command from the service as internally it just enums all processes and kills them one by one. So really one only needs to talk to the driver to do everything.

> what happened to the license header?
the file wasn't a copy but a frankensteinian contraption of code snippets, and then negligence struck, its fixed now.

**Comment by DavidXanatos** [comment] 2021-07-23 18:41
with this changed the plugin works again with modern sbie versions: https://github.com/processhacker/plugins-extra/pull/91

**Comment by dmex** [comment] 2021-07-24 00:44
> best approche to load the SbieDll.dll just to use a few API's as then updating sandboxie will prompt to kill process hacker if its running.

Does this also happen when the driver has an open handle? Ideally we would open a handle/load the DLL then call the function and immediately unload the DLL/close the handle.

>  the plugin works again with modern sbie versions

LGTM

I'll close the issue now that it's resolved. Thanks for taking the time to look into the bugs and fix up the code @DavidXanatos 😀

**Closed by dmex** 2021-07-24 00:44 UTC

**Comment by DavidXanatos** [comment] 2021-07-24 05:51
Well there are two things, one is the setups urge to kill all processes that have the SbieDll.dll loaded, the second is that indeed as long as the handle on the driver is open it cant be unloaded, but the setup tries to unload it multiple times, and the new code opens the handle only very shortly when it wants something. So that must be fine.
My TE uses the same approach and i have it runnign in the background and when unloading and reloading the driver 1000 times a day during development is worked every time, sometimes it just took a moment longer to unload.

**Comment by kristibektashi** [comment] 2021-07-26 13:11
@dmex Now that Sandboxie plugin works will it be added back to Process Hacker by default or not? Cuz Visual Studio takes a lot of space that I need for other things

**Comment by Biswa96** [comment] 2021-07-26 13:20
You could setup a CI workflow to compile plugins-extra which does not have that now.

**Comment by isaak654** [comment] 2021-09-13 13:46
> 
> 
> You could setup a CI workflow to compile plugins-extra which does not have that now.

That's the issue, it can't be done without merging the following pull requests:
https://github.com/processhacker/plugins-extra/pull/92 
https://github.com/processhacker/plugins-extra/pull/93 
https://github.com/processhacker/plugins-extra/pull/94
