### ISSUE TITLE
Find handles or DLLs and System info windows do not display properly

### ISSUE THREAD

**Issue by mblissmer** [processhacker/processhacker#358] opened 2019-01-07 16:23 UTC
On a Server 2012 R2 Standard machine, 48gb RAM, 64-bit OS.

If you try to open either of those windows, they show incorrectly, I'm not sure how to describe it, see attached screenshot. These popup windows work fine on my local Win7x64 machine, but not on the above server.

![image](https://user-images.githubusercontent.com/7719185/50779531-9494e800-126e-11e9-98eb-fbae6a73d1c5.png)

**Comment by dmex** [comment] 2019-01-07 17:42
> If you try to open either of those windows, they show incorrectly, I'm not sure how to describe it,

It's an issue caused by GDI object handles.

> Server 2012 R2 Standard machine, 48gb RAM, 64-bit OS.

Have you tried the nightly build?
https://wj32.org/processhacker/nightly.php

**Comment by mblissmer** [comment] 2019-01-07 18:58
Nice, the nightly works great. 
GDI handles on the bugged version is 10,000?
Also, that window does the same thing, so it took me a few tries to see the right number.
GDI handles on the nightly is 5533

Personally, since nightly did the trick, I consider this resolved, unless you want to leave it open for some reason. Thanks for the VERY fast reply!

**Comment by dmex** [comment] 2019-01-07 19:17
> GDI handles on the bugged version is 10,000?

Windows has a maximum limit of 10,000 😄 

> Personally, since nightly did the trick, I consider this resolved, unless you want to leave it open for some reason. 

There's still an issue with caching GDI object handles. I made some changes last year to the nightly builds that improved the caching but it needs to be a lot more aggressive.

I'll close the ticket when those changes are eventually committed 👍

**Comment by Biswa96** [comment] 2019-01-07 19:25
Registry that limits GDI objects per-process: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\GDIProcessHandleQuota`

**Comment by dmex** [comment] 2019-01-08 17:55
@Biswa96 

The problem is with how treenew.c caches icon handles not the default Windows GDI limits 🤔

**Comment by dmex** [comment] 2019-05-21 18:34
Recent nightly builds include some fixes for the Disk and Network tabs and reduces the GDI usage by a factor of 3... The last remaining issue is with the treelist control GDI usage.

**Closed** 2020-11-22 15:37 UTC
Labels: bug

**Comment by dmex** [comment] 2020-11-22 15:45
Fixed in the nightly builds 👍
