### ISSUE TITLE
Icons missing in Processes tab

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [processhacker/processhacker#741] opened 2020-11-23 18:53 UTC
Since version 3.0.3615 icons are missing in Processes tab.

**Comment by dmex** [comment] 2020-11-23 19:03
Deleted the nondefault plugins?

**Comment by Bec-de-Xorbin** [comment] 2020-11-23 19:12
I didn't delete anything. I also did a clean install in Windows Sandbox and processes' icons are missing there also. 3.0.3613 works ok.

**Comment by dmex** [comment] 2020-11-24 09:00
Can you try version 3.0.3620?

**Comment by Bec-de-Xorbin** [comment] 2020-11-24 19:01
I tried 3.0.3620 and 3.0.3625, icons missing on both.

**Comment by dmex** [comment] 2020-11-24 19:44
Which version of windows?

**Comment by Bec-de-Xorbin** [comment] 2020-11-24 19:45
Version 20H2 (OS Build 19042.662).

**Comment by lespea** [comment] 2020-11-24 20:19
Same for 3625.  I tried disabled theme support, then cleaning settings, then reset all settings, and all icons are missing.

**Comment by dmex** [comment] 2020-11-24 22:27
I've tested Windows 7, 8 and 10 but can't reproduce the issue.

**Comment by lespea** [comment] 2020-11-24 22:32
The monitor is 4k using a dpi of 150% if that is relevant?  I can try to test more things when I'm done working later today

**Comment by dmex** [comment] 2020-11-24 22:33
> 4k using a dpi of 150%

Try changing the DPI and any other settings.

**Comment by ts03GCZqIsTZtu4** [comment] 2020-11-24 23:18
mine did this as soon as i updated it. every icon went away, a reinstall changed nothing.

**Comment by dmex** [comment] 2020-11-25 00:22
Fixed in 3.0.3627 and above 👍

**Closed by dmex** 2020-11-25 00:22 UTC
Labels: bug

**Comment by Bec-de-Xorbin** [comment] 2021-04-27 23:44
Missing again in 3.0.4016. Worked ok in 3.0.4000. Seems like DPI issue again, 100% scaling ok, 125% not ok.

**Comment by dmex** [comment] 2021-04-28 05:50
@Bec-de-Xorbin 

Fixed in r4017
