### ISSUE TITLE
Is this normal ?

### ISSUE THREAD

**Issue by Mrsmartcoder** [processhacker/processhacker#842] opened 2021-03-22 08:00 UTC
Whenever i have process hacker in my computer shutting down and restarting takes about 5-10 minutes ! I really dont know why this happend but if i uninstalled/remove process hacker shutting down and restarting would just fix it but i really want to use this software.

**Comment by Biswa96** [comment] 2021-03-22 08:08
Never seen this issue. Did you add ProcessHacker in autostart program list? The list can be seen Task Manager.

**Comment by dmex** [comment] 2021-03-22 08:22
What security software do you have installed?

**Comment by dmex** [comment] 2021-03-22 20:49
> process hacker in my computer shutting down and restarting takes about 5-10 minutes

Windows forcefully terminates applications after 20 seconds during shutdown and Process Hacker can't do anything to delay or stop shutdown.

What security software do you have installed?

**Comment by Mrsmartcoder** [comment] 2021-03-23 05:12
> > process hacker in my computer shutting down and restarting takes about 5-10 minutes
> 
> Windows forcefully terminates applications after 20 seconds during shutdown and Process Hacker can't do anything to delay or stop shutdown.
> 
> What security software do you have installed?

Security ? antivirus ? If so i got Bitdefender free version but just yesterday it removes process hacker which is new to me because it never happend before

**Comment by Mrsmartcoder** [comment] 2021-03-23 05:13
> Never seen this issue. Did you add ProcessHacker in autostart program list? The list can be seen Task Manager.

Yea i enable it

**Comment by dmex** [comment] 2021-03-30 17:34
I'm closing this as unreproducible. I've tested 6 machines this week and cannot reproduce this behaviour. The issue is likely some third party software outside our control that's causing the issue.

**Closed by dmex** 2021-03-30 17:34 UTC
Labels: needs reproduction

**Comment by TheEnderek0** [comment] 2021-04-14 17:06
On my computer it happened too. I fixed it by going to options in Process Hacker and Advanced, then unchecking "Enable Kernel mode driver". Though it the computer couldn't shutdown entirely, waiting did nothing.

**Comment by dmex** [comment] 2021-04-15 03:24
> I fixed it by going to options in Process Hacker and Advanced, then unchecking "Enable Kernel mode driver"

Yeah, don't bother looking for the rootkit patching our kernel driver that's actually screwing up the shutdown... Just disable the Process Hacker driver so the rootkit doesn't patch it and your machine magically starts working properly 😄

**Comment by TheEnderek0** [comment] 2021-04-15 18:02
Well I didn't search for it because I didn't knew it existed.

**Comment by Searchcat37** [comment] 2022-03-06 16:44
For me, I found that running `powercfg.exe /hibernate off` fixes it
