### ISSUE TITLE
Request: decrease minimum size of "System Information" window

### ISSUE THREAD

**Issue by token0** [processhacker/processhacker#477] opened 2019-09-22 10:47 UTC
Because it's default minimum size is huge. I would consider to make it as low as 200 px on X-axis.
Thanks!

**Comment by dmex** [comment] 2019-10-04 08:02
What size screen are you using?

**Comment by token0** [comment] 2019-10-08 20:10
24" WUXGA

**Comment by token0** [comment] 2019-10-11 10:34
Well, built it with this changes, now I'm happy.
sysinfo.c @425-426
```
- MinimumSize.right = 430;
- MinimumSize.bottom = 290;
+ MinimumSize.right = 43; //430
+ MinimumSize.bottom = 29; //290
```

**Comment by dmex** [comment] 2020-11-24 09:11
Duplicate of #659

**Closed by dmex** 2020-11-24 09:11 UTC
