### ISSUE TITLE
Process hacker 2.0 and 3 High Cpu Usage % when on Tray icon

### ISSUE THREAD

**Issue by x8009** [processhacker/processhacker#1011] opened 2021-10-16 09:45 UTC
the program is terribly slow compared to Process Hacker 2, when reaching the HACKER there is always a 1-2 sec delay compared to Process Hacker 2 in instant, also compared to an older version of process hacker 3.

when not using Process Hacker 3 I noticed I have higher FPS in games and better Windows performance or more fluid, I also noticed Remote desktop worked better which I didn't know why I have weird delays until I saw Process Hacker 3 wasn't running.

At the moment I am using Process Hacker 2 it's the same performance as it's not running. Process Hacker 3 running reduces all computer performance, higher memory latency, higher CPU usage, FPS reduction in games at the start, and even more over time. It's very unstable now, for an unknown time when it started.

Process Hacker 2 Started to do the same issue with high CPU usage on Tray Icon and FPS Drop because of this. so it's not just process hacker 3

https://i.imgur.com/weXIzvY.png

https://wj32.org/processhacker/forums/viewtopic.php?t=4441

**Comment by x8009** [comment] 2021-10-16 10:35
I see it was investigated before

https://github.com/processhacker/processhacker/issues/641

**Comment by dmex** [comment] 2022-02-28 10:10
Duplicate of #641

**Closed by dmex** 2022-02-28 10:10 UTC
